language: go
go:
  - 1.9.x
  - 1.10.x

services:
  - docker

addons:
  apt:
    packages:
    - rpm

matrix:
  allow_failures:
    - go: release
    - go: tip
  fast_finish: true

env:
  matrix:
    - GOCD_URL=http://127.0.0.1:8153/go/
    - GOCD_URL=https://127.0.0.1:8154/go/ GOCD_SKIP_SSL_CHECK=1
  global:
    - secure: ax6R000Lq+b4jbOKXxXBFyWKAQdPQkdwxSqy7qukPKk9fOh5mXI/gEX7ep6JHRvcBqbq5LavXgNCQpyGdTevhdi8eQBhvOE79one/bLbDYj4mCbDu2rHtk3Dln3+xWTIhe2HFembCxcVHLHK8zAv8vSadJN/bDEGGTdfkZS+h3GW5LKhtcD3j3prJ6baJUkmGiiOt7kDcYEYkXMDaS13fM9E/G8GD0hI7YrwUJ5HY1EMBcUjHiFUDwSLM6OqF4bKbDxVcsVNwh5SLSTG4PDMmdKDP3suTgQZauGuzCL51KjsYIdC9wGkFnUK2BLM++7CkYjsrVAAGEWoQhPhjIi5psuQbaGYrvtbSbjb6Zx2jjtbzTJJ1KtIRcjzkiFKF6EhG8+HAlfSubBSMov+geoj5VXbMgCT7Pwnzf7I4kKd+xUYvKZ8Zda3OrXk2iY9qJ+WGCgtb38rHsgE1bLIVcdZyX0cNcTQZmCvTny81teZNuIS5zWbOyZxwnRVaDv51uvs+YL1+zwgBmSR2dzef5NN4eUxzip93/FhBDmqYxpu7XWtMMrI5roWsmpWNL0DACf8qIDRYtGR2Wr+oC+uadG8aqEiCp5vPmgsPmOwvatOqAScuR5J2bYylDqtseFKUuWoYPNT6BfTk+ZMLv9r08230+W5SmF2/KIzJm0OjRc/OLw=

cache:
  pip: true

before_install:
  - openssl aes-256-cbc -K $encrypted_b7c1913c3ccb_key -iv $encrypted_b7c1913c3ccb_iv -in .gitcookies.enc -out $HOME/.gitcookies -d
  - make before_install

script:
  - make vet
  - make script

after_failure:
  - make after_failure

after_success:
  - make after_success

deploy:
  # We do a `skip_cleanup` because when the docker-compose runs, it creates files in the host file system with the
  # userid `1000`. Our travis user does not have the userid `1000`, so it can not clean those files up, causing the
  # deploy to break. We do a `git clean` from the Makefile to perform necessary cleanup.
  - provider: script
    skip_cleanup: true
    script: make deploy_on_tag
    on:
      tags: true
      condition: $TRAVIS_GO_VERSION =~ ^1\.10\.([0-9]+|x)?$ && $GOCD_SKIP_SSL_CHECK = 1
  - provider: script
    skip_cleanup: true
    script: make deploy_on_develop
    on:
      branch: develop
