version: '3'
services:
  gocd-server:
    image: gocd/gocd-server:v17.7.0
    ports:
     - "8153:8153"
     - "8154:8154"
    volumes:
     - ./godata/server:/godata
  gocd-agent1:
    image: gocd/gocd-agent-ubuntu-16.04:v17.7.0
    links:
      - gocd-server:server
    depends_on:
      - gocd-server
    environment:
      AGENT_AUTO_REGISTER_KEY: fca06912-b3e8-454d-b397-5708f1807a24
      GO_SERVER_URL: https://server:8154/go
  gocd-agent2:
    image: gocd/gocd-agent-ubuntu-16.04:v17.7.0
    links:
      - gocd-server:server
    depends_on:
      - gocd-server
    environment:
      AGENT_AUTO_REGISTER_KEY: fca06912-b3e8-454d-b397-5708f1807a24
      GO_SERVER_URL: https://server:8154/go
